version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html # Adjust path as needed
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 60
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/configure_laravel.sh
      timeout: 60
