name: Deploy Northstar

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 - Northstar
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create deployment directory
            mkdir -p ~/deployment

            # Clone the repository to get the deployment scripts
            rm -rf ~/deployment/repos
            git clone  https://github.com/segunemma2003/samschool.git ~/deployment/repos

            # Make deployment script executable and run it
            chmod +x ~/deployment/repos/deploy-site2.sh

            sudo mkdir -p /var/www/northstar
            sudo chown -R $USER:$USER /var/www/northstar

            ~/deployment/repos/deploy-site2.sh
