name: Laravel Deployment
on:
 push:
 branches:
 - main
jobs:
 deploy:
 runs-on: ubuntu-latest
steps:
 - name: Checkout repository
 uses: actions/checkout@v2
- name: Set up PHP
 uses: shivammathur/setup-php@v2
 with:
 php-version: '8.3'
- name: Install dependencies
 run: composer install - no-dev
- name: Set up AWS CLI
 uses: aws-actions/configure-aws-credentials@v1
 with:
 aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
 aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 aws-region: ${{ secrets.AWS_REGION }}
- name: Deploy to AWS EC2
 run: ssh ${{ secrets.AWS_INSTANCE_IP }} "mkdir -p /var/www/html && cd /var/www/html && git pull && composer install - no-dev"
